### ISSUE TITLE
Bokeh serialisation KeyError in interactivity tutorial

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#6579]
It looks like this example is currently broken?

https://holoviz-dev.github.io/panel/tutorials/intermediate/interactivity.html

<img width="2260" alt="Screenshot 2024-03-26 at 08 45 59" src="https://github.com/holoviz/panel/assets/852409/25e97cfd-6523-48df-84e6-3b1ad9299e8e">

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 393, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 7, in <module>
  File "/lib/python3.11/site-packages/bokeh/document/document.py", line 374, in apply_json_patch
    patch: PatchJson = deserializer.deserialize(patch_json)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 520, in deserialize
    return self.decode(obj)
           ^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 533, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 574, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 574, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 576, in _decode
    return [self._decode(entry) for entry in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 576, in <listcomp>
    return [self._decode(entry) for entry in obj]
            ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 574, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 574, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 555, in _decode
    return self._decode_map(cast(MapRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 606, in _decode_map
    return { self._decode(key): self._decode(val) for key, val in entries }
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 606, in <dictcomp>
    return { self._decode(key): self._decode(val) for key, val in entries }
                                ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 563, in _decode
    return self._decode_ndarray(cast(NDArrayRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 667, in _decode_ndarray
    decoded = self._decode(array)
              ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in _decode
    return self._decode_bytes(cast(BytesRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/serialization.py", line 616, in _decode_bytes
    id = data["id"]
         ~~~~^^^^^^
KeyError: 'id'

    at new_error (pyodide.asm.js:9:10014)
    at pyodide.asm.wasm:0x158e62
    at pyodide.asm.wasm:0x15ff9e
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:9:120223)
    at pyodide.asm.wasm:0x1a3494
    at pyodide.asm.wasm:0x28a2bd
    at pyodide.asm.wasm:0x1e431e
    at pyodide.asm.wasm:0x1a397d
    at pyodide.asm.wasm:0x1a3c3e
    at pyodide.asm.wasm:0x1a3ce0
    at pyodide.asm.wasm:0x2689a4
    at pyodide.asm.wasm:0x26e800
    at pyodide.asm.wasm:0x1a3e08
    at pyodide.asm.wasm:0x1a3a98
    at pyodide.asm.wasm:0x15f76b
    at Module.callPyObjectKwargs (pyodide.asm.js:9:64297)
    at Module.callPyObject (pyodide.asm.js:9:65365)
    at wrapper (pyodide.asm.js:9:32855)
```

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz-dev/nbsite/pull/305

**Comment by philippjfr** [comment]
Will reopen until a new doc build confirms the fix.

**Comment by Jake-Moss** [comment]
I'm running something similar to this in another project when using the FileDropper widget in a pyodide environment, the stack trace is very similar. When served via `panel serve` the widget works file. This can be reproduced in the documentation on the FileDropper page.

```
bokeh: 3.7.2
panel: 1.6.2
```

```
PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 597, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 411, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 10, in <module>
  File "/lib/python3.12/site-packages/bokeh/document/document.py", line 374, in apply_json_patch
    patch: PatchJson = deserializer.deserialize(patch_json)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 515, in deserialize
    return self.decode(obj)
           ^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 528, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 569, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 571, in _decode
    return [self._decode(entry) for entry in obj]
            ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 569, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 538, in _decode
    return self._decoders[type](obj, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/events.py", line 200, in from_serializable
    decoded_values = decoder.decode(values)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 523, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 550, in _decode
    return self._decode_map(cast(MapRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 601, in _decode_map
    return { self._decode(key): self._decode(val) for key, val in entries }
                                ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 550, in _decode
    return self._decode_map(cast(MapRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 601, in _decode_map
    return { self._decode(key): self._decode(val) for key, val in entries }
                                ^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 552, in _decode
    return self._decode_bytes(cast(BytesRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/bokeh/core/serialization.py", line 611, in _decode_bytes
    id = data["id"]
         ~~~~^^^^^^
KeyError: 'id'
pyodide.asm.js:10:50765
```

https://panel.holoviz.org/reference/widgets/FileDropper.html

![Image](https://github.com/user-attachments/assets/fb9c4213-3a7f-4765-83ca-981e09ab63cb)

**Comment by JL2435** [comment]
Hey, Is there any update on this issue? . I'm still getting this same serialization error when running in WASM.  I've tried the filedropper on the documentation page and on a local app using the following Panel/Bokeh version's

bokeh: 3.8.1
panel: 1.8.3
